//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public int AreaId { get; set; }
        public string AreaName { get; set; }
        public Nullable<short> CountryId_fk { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
