//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCustomer
    {
        public int ProductCustomerId { get; set; }
        public Nullable<int> CustomerId_fk { get; set; }
        public Nullable<int> ProductId_fk { get; set; }
        public Nullable<int> ModelId_fk { get; set; }
        public Nullable<int> OfferId_fk { get; set; }
        public Nullable<System.DateTime> SalesDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Model Model { get; set; }
        public virtual Offer Offer { get; set; }
        public virtual Product Product { get; set; }
    }
}
